### ISSUE TITLE
Snake and Ladder Game

### ISSUE THREAD

**Issue by anjareddy** [gregdelozier/summer-project#14]
This can be using a table on the UI.
UI page is game area.
Table with 8X8 as board in the game.
Each cell is a position.
User can roll a die by clicking on a button on page.
On rolling die, user image moves to the tile (cell) based on the value.
We use browser memory to store players info like, name and current location.

**Comment by gregdelozier** [comment]
Do we need animation?

**Comment by anjareddy** [comment]
No animation is required

**Comment by anjareddy** [comment]
User can roll a die by clicking on button that generates a random number between 1 and 6 and moves player to respective cell.

**Comment by anjareddy** [comment]
Board can be 10*10.
