### ISSUE TITLE
Dice Roll

### ISSUE THREAD

**Issue by jsipahio** [gregdelozier/summer-project#32]
There needs to be a way for the player to receive a value between 1 and 6 to know how many spaces they can move

**Acceptance Criteria:**
On clicking on the dice button, it has to generate a random number from 1 to 6 and display the number on the screen. The automated test will check if the generated number is in the range [1, 6]

**Comment by gregdelozier** [comment]
How will we know we are done?

**Comment by jsipahio** [comment]
It is done when there is a button that can be pushed, that then displays the result of the roll of the die.

**Comment by anjareddy** [comment]
Acceptance Criteria:
On clicking on the dice button, it has to generate a random number from 1 to 6 and display the number on the screen.

**Comment by jagadeesh3921** [comment]
Working on dice roll animation, exploring 3d animation of the dice roll on clicking dice button.

**Comment by jagadeesh3921** [comment]
Dice rotation is done, working on matching the die's face value to the result.
