### ISSUE TITLE
Mark snakes on board

### ISSUE THREAD

**Issue by jsipahio** [gregdelozier/summer-project#37]
The locations of where the snakes occur can be represented visually on the game board. Depends on being able to initially draw the board and generate snake locations. It is done when there is some visual representation of where the snakes occur on the board.

**Acceptance**: 

1. The ladder is should look like the image attached below. Visually the ladder should start on a lower cell and end on a higher cell. The test is done by visual inspection by a human.

![Image](https://github.com/gregdelozier/summer-project/assets/31825416/114a1f18-1bb6-4e06-ab71-ff742874e516)

**Comment by redwanulsourav** [comment]
Commit daf345db790abd32aaf1ba7705abd00d839017db solved this issue.
