### ISSUE TITLE
Draw player

### ISSUE THREAD

**Issue by jsipahio** [gregdelozier/summer-project#42]
Put a visual representation of the player on the board that signifies their current position on the board. It is done when the player piece (whatever the representation is) can be viewed on the board. The test can be done by visual inspection by a human.

**Comment by SrinithaP1** [comment]
I will take up this and try working on it.

**Comment by redwanulsourav** [comment]
Done in Commit 7df4fbf4d385804b57ba1903ce332456b0b42f5b
